version: '3'
services:
    # https://github.com/wpcomvip/nbcots/
    mysql-lx:
        container_name: nbc-wp-mysql-lx
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        image: mariadb:10.4
        restart: always
        volumes:
            - db-lx:/var/lib/mysql
            - .logs/mysql-lx:/var/log/mysql
        networks:
            - nbc-wp-lx
        ports:
            - 33307:3306
        healthcheck:
            test: mysqlshow -p$MYSQL_ROOT_PASSWORD
            interval: 5s
            timeout: 5s
            retries: 3

    wordpress-lx:
        container_name: nbc-wp-php-lx
        depends_on:
            - mysql-lx
        environment:
            WORDPRESS_DB_HOST: mysql-lx
            WORDPRESS_DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            WORDPRESS_CONFIG_EXTRA: require_once( ABSPATH . 'wp-content/vip-config/vip-config.php' );
        image: nbc-wordpress
        build:
            context: ./setup/docker/wordpress
        restart: always
        volumes:
            - ./wp-container-lx:/var/www/html
            - ./conf/php.ini:/usr/local/etc/php/conf.d/wp.ini
        networks:
            - nbc-wp-lx
        healthcheck:
            test: env SCRIPT_NAME=/var/www/html/wp-admin/index.php SCRIPT_FILENAME=/var/www/html/wp-admin/index.php REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000
            interval: 10s
            timeout: 10s
            retries: 3

    nginx-lx:
        container_name: nbc-wp-nginx-lx
        depends_on:
            - wordpress-lx
            - memcached-lx
        image: nginx:alpine
        ports:
            - '81:81'
            - '444:444'
        restart: always
        volumes:
            - ./conf/nginx/nginx-lx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/certs:/etc/nginx/ssl
            - ./wp-container-lx:/var/www/html
            - .logs/nginx-lx:/var/log/nginx
        networks:
            - nbc-wp-lx

    memcached-lx:
        container_name: nbc-wp-memcached-lx
        depends_on:
            - wordpress-lx
        image: memcached:alpine
        restart: always
        ports:
            - '11212:11211'

    wp-cli-lx:
        container_name: nbc-wp-cli-lx
        image: wordpress:cli
        restart: on-failure
        volumes:
            - ./wp-container-lx:/var/www/html
            - ./docker_init.sh:/var/www/html/init.sh
        command: /var/www/html/init.sh
        environment:
            WORDPRESS_DB_HOST: mysql-lx
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            LOCAL_DEV_DOMAIN: '${LOCAL_DEV_DOMAIN}:81'
            WP_SITE_TITLE: $WP_SITE_TITLE
            WP_ADMIN_USER: $WP_ADMIN_USER
            WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
            WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
            WP_IS_MULTISITE: $WP_IS_MULTISITE
            WP_IS_MULTISITE_SUBDOMAIN: $WP_IS_MULTISITE_SUBDOMAIN
            WP_PROJECT_THEME_FOLDER: localx
        networks:
            - nbc-wp-lx

    phpmyadmin-lx:
        container_name: nbc-wp-phpmyadmin-lx
        depends_on:
            - wordpress-lx
            - mysql-lx
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8890:80'
        environment:
            PMA_HOST: mysql-lx
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        networks:
            - nbc-wp-lx

networks:
    nbc-wp-lx:

volumes:
    db-lx:
    logs-lx:
    wp-container-lx:
