version: '3'
services:
    # https://github.com/wpcomvip/nbcots/
    mysql-microsites:
        container_name: nbc-wp-mysql-microsites
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        image: mariadb:10.4
        restart: always
        volumes:
            - db-microsites:/var/lib/mysql
            - .logs/mysql-microsites:/var/log/mysql
        networks:
            - nbc-wp-microsites
        ports:
            - 33308:3306
        healthcheck:
            test: mysqlshow -p$MYSQL_ROOT_PASSWORD
            interval: 5s
            timeout: 5s
            retries: 3

    wordpress-microsites:
        container_name: nbc-wp-php-microsites
        depends_on:
            - mysql-microsites
        environment:
            WORDPRESS_DB_HOST: mysql-microsites
            WORDPRESS_DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            WORDPRESS_CONFIG_EXTRA: require_once( ABSPATH . 'wp-content/vip-config/vip-config.php' );
        image: nbc-wordpress
        build:
            context: ./setup/docker/wordpress
        restart: always
        volumes:
            - ./wp-container-microsites:/var/www/html
            - ./conf/php.ini:/usr/local/etc/php/conf.d/wp.ini
        networks:
            - nbc-wp-microsites
        healthcheck:
            test: env SCRIPT_NAME=/var/www/html/wp-admin/index.php SCRIPT_FILENAME=/var/www/html/wp-admin/index.php REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000
            interval: 10s
            timeout: 10s
            retries: 3

    nginx-microsites:
        container_name: nbc-wp-nginx-microsites
        depends_on:
            - wordpress-microsites
            - memcached-microsites
        image: nginx:alpine
        ports:
            - '82:82'
            - '445:445'
        restart: always
        volumes:
            - ./conf/nginx/nginx-microsites.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/certs:/etc/nginx/ssl
            - ./wp-container-microsites:/var/www/html
            - .logs/nginx-microsites:/var/log/nginx
        networks:
            - nbc-wp-microsites

    memcached-microsites:
        container_name: nbc-wp-memcached-microsites
        depends_on:
            - wordpress-microsites
        image: memcached:alpine
        restart: always
        ports:
            - '11213:11211'

    wp-cli-microsites:
        container_name: nbc-wp-cli-microsites
        image: nbc-wordpress:cli
        build:
            context: ./setup/docker/wordpress
            dockerfile: wordpress-cli.Dockerfile
        restart: on-failure
        volumes:
            - ./wp-container-microsites:/var/www/html
            - ./docker_init.sh:/var/www/html/init.sh
        command: /var/www/html/init.sh
        environment:
            WORDPRESS_DB_HOST: mysql-microsites
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            LOCAL_DEV_DOMAIN: '${LOCAL_DEV_DOMAIN}:82'
            WP_SITE_TITLE: $WP_SITE_TITLE
            WP_ADMIN_USER: $WP_ADMIN_USER
            WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
            WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
            WP_IS_MULTISITE: $WP_IS_MULTISITE
            WP_IS_MULTISITE_SUBDOMAIN: $WP_IS_MULTISITE_SUBDOMAIN
            WP_PROJECT_THEME_FOLDER: supporting-our-schools
        networks:
            - nbc-wp-microsites

    phpmyadmin-microsites:
        container_name: nbc-wp-phpmyadmin-microsites
        depends_on:
            - wordpress-microsites
            - mysql-microsites
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8891:80'
        environment:
            PMA_HOST: mysql-microsites
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        networks:
            - nbc-wp-microsites

networks:
    nbc-wp-microsites:

volumes:
    db-microsites:
    logs-microsites:
    wp-container-microsites:
