version: '3'
services:
    mysql:
        container_name: nbc-wp-mysql
        environment:
            MYSQL_DATABASE: 'wordpress'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        image: mariadb:10.4
        restart: always
        volumes:
            - .data:/var/lib/mysql
            - .logs/mysql:/var/log/mysql
        networks:
            - nbc-wp

    wordpress:
        container_name: nbc-wp-php
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        image: 'wordpress:5.2.2-fpm'
        restart: always
        volumes:
            - ./wp-container:/var/www/html
            - ./conf/php.ini:/usr/local/etc/php/conf.d/wp.ini
        networks:
            - nbc-wp

    nginx:
        container_name: nbc-wp-nginx
        depends_on: 
            - wordpress
            - memcached
        image: nginx:alpine
        ports:
            - '80:80'
            - '443:443'
        restart: always
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/certs:/etc/nginx/ssl
            - ./wp-container:/var/www/html
            - .logs/nginx:/var/log/nginx
        networks:
            - nbc-wp

    memcached:
        container_name: nbc-wp-memcached
        depends_on:
            - wordpress
        image: memcached:alpine
        restart: always
        ports:
            - '11211:11211'

    wp-cli:
        container_name: nbc-wp-cli
        image: wordpress:cli
        restart: on-failure
        volumes:
            - ./wp-container:/var/www/html
            - ./docker_init.sh:/var/www/html/init.sh
        command: /var/www/html/init.sh
        depends_on:
            - mysql
            - wordpress
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            LOCAL_DEV_DOMAIN: $LOCAL_DEV_DOMAIN
            WP_SITE_TITLE: $WP_SITE_TITLE
            WP_ADMIN_USER: $WP_ADMIN_USER
            WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
            WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
            WP_IS_MULTISITE: $WP_IS_MULTISITE
            WP_IS_MULTISITE_SUBDOMAIN: $WP_IS_MULTISITE_SUBDOMAIN
            WP_PROJECT_THEME_FOLDER: $WP_PROJECT_THEME_FOLDER
        networks:
            - nbc-wp

    phpmyadmin:
        container_name: nbc-wp-phpmyadmin
        depends_on:
            - wordpress
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8889:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        networks:
            - nbc-wp

networks:
    nbc-wp:

volumes:
    db:
    logs:
    wp-container:
